import Navbar from "@/components/Sections/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/Sections/Footer";
import { Providers } from "./providers";
 

export const metadata = {
  title: "Gatwech Tap Nguth's Portfolio website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
   return (
    <html lang="en">
      <body className="bg-white dark:bg-gray-800 ">
        <Providers>
           {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
